packages:
  - libs/*
  - apps/*
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - bcrypt
  - nx
  - unrs-resolver
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
