packages:
  - "libs/*"
  - "apps/*"

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - bcrypt
  - nx
  - unrs-resolver

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
